//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMIAutomation.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMIAutomation.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abdomen.
        /// </summary>
        public static string Abdomen {
            get {
                return ResourceManager.GetString("Abdomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to above knees.
        /// </summary>
        public static string AboveKnees {
            get {
                return ResourceManager.GetString("AboveKnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below knees.
        /// </summary>
        public static string BelowKnees {
            get {
                return ResourceManager.GetString("BelowKnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BODY.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;user origin distance &gt; 12 cm from nearest isocenter&gt;.
        /// </summary>
        public static string DefaultLowerMarkerLocationMsg {
            get {
                return ResourceManager.GetString("DefaultLowerMarkerLocationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;user origin distance &gt; 10 cm from nearest isocenter&gt;.
        /// </summary>
        public static string DefaultUpperMarkerLocationMsg {
            get {
                return ResourceManager.GetString("DefaultUpperMarkerLocationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacements: Isocenters.
        /// </summary>
        public static string DisplacementsHeader {
            get {
                return ResourceManager.GetString("DisplacementsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to head.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isocenter.
        /// </summary>
        public static string Isocenter {
            get {
                return ResourceManager.GetString("Isocenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark isocenter position on the mask.
        /// </summary>
        public static string IsoOnArmsMarkerWarning {
            get {
                return ResourceManager.GetString("IsoOnArmsMarkerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on LEFT arm.
        /// </summary>
        public static string IsoOnLeftArm {
            get {
                return ResourceManager.GetString("IsoOnLeftArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on RIGHT arm.
        /// </summary>
        public static string IsoOnRightArm {
            get {
                return ResourceManager.GetString("IsoOnRightArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGS.
        /// </summary>
        public static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most caudal isocenter from markers.
        /// </summary>
        public static string MostCaudalIsoFromMarkers {
            get {
                return ResourceManager.GetString("MostCaudalIsoFromMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move by:.
        /// </summary>
        public static string MoveBy {
            get {
                return ResourceManager.GetString("MoveBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;new course...&gt;.
        /// </summary>
        public static string NewCourseListBox {
            get {
                return ResourceManager.GetString("NewCourseListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on knees.
        /// </summary>
        public static string OnKnees {
            get {
                return ResourceManager.GetString("OnKnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pelvis.
        /// </summary>
        public static string Pelvis {
            get {
                return ResourceManager.GetString("Pelvis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shoulders.
        /// </summary>
        public static string Shoulders {
            get {
                return ResourceManager.GetString("Shoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thorax.
        /// </summary>
        public static string Thorax {
            get {
                return ResourceManager.GetString("Thorax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toward back of the patient.
        /// </summary>
        public static string TowardBackOfPatient {
            get {
                return ResourceManager.GetString("TowardBackOfPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toward feet of the patient.
        /// </summary>
        public static string TowardFeetOfPatient {
            get {
                return ResourceManager.GetString("TowardFeetOfPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toward front of the patient.
        /// </summary>
        public static string TowardFrontOfPatient {
            get {
                return ResourceManager.GetString("TowardFrontOfPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toward head of the patient.
        /// </summary>
        public static string TowardHeadOfPatient {
            get {
                return ResourceManager.GetString("TowardHeadOfPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toward left of the patient.
        /// </summary>
        public static string TowardLeftOfPatient {
            get {
                return ResourceManager.GetString("TowardLeftOfPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toward right of the patient.
        /// </summary>
        public static string TowardRightOfPatient {
            get {
                return ResourceManager.GetString("TowardRightOfPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With respect to isocenter.
        /// </summary>
        public static string WrtIsocenter {
            get {
                return ResourceManager.GetString("WrtIsocenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With respect to markers.
        /// </summary>
        public static string WrtMarkersNear {
            get {
                return ResourceManager.GetString("WrtMarkersNear", resourceCulture);
            }
        }
    }
}
