// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TMIAutomation.Model.Schedule.Templates
{
    using System.Linq;
    using VMS.TPS.Common.Model.Types;
    using TMIAutomation.Language;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DisplacementsPage : DisplacementsPageBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(patient.FirstName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 7 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(patient.LastName));
            
            #line default
            #line hidden
            this.Write(" TMLI ");
            
            #line 7 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(treatmentDate.ToString("D")));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\r\n");
            
            #line 10 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.DisplacementsHeader));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 10 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.Body));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 12 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.MostCaudalIsoFromMarkers));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 12 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(upperMarkersLocation));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 12 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Math.Abs(Math.Round(upperIsocenters.Last().z, 0)) / 10));
            
            #line default
            #line hidden
            this.Write(" cm\r\n");
            
            #line 13 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.Notes));
            
            #line default
            #line hidden
            this.Write(": ...\r\n");
            
            #line 14 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

for (int i = 0; i < upperIsocenters.Count; ++i)
{
VVector displacement = new VVector();
string explainDisp = string.Empty;
if (i == 0)
{
    displacement = upperIsocenters[i];
    explainDisp =  string.Join(" ", Resources.WrtMarkersNear, upperMarkersLocation, Resources.MoveBy);
}
else if (isocentersOnArms && i == upperIsocenters.Count - 1)
{
    /*
     * Skip isocenters on the arms to compute displacement
     * of last iso wrt previous iso along the body
     */
    displacement = upperIsocenters[i] - upperIsocenters[i - 3];
    explainDisp =  string.Join(" ", Resources.WrtIsocenter, i - 2, Resources.MoveBy); // i - 2 for correct iso number strating from 1
}
else
{
    displacement = upperIsocenters[i] - upperIsocenters[i - 1];
    explainDisp =  string.Join(" ", Resources.WrtIsocenter, i, Resources.MoveBy);
}
double roundedDispX = Math.Abs(Math.Round(displacement.x, 0)) / 10;
double roundedDispY = Math.Abs(Math.Round(displacement.y, 0)) / 10;
double roundedDispZ = Math.Abs(Math.Round(displacement.z, 0)) / 10;

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.Isocenter));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 43 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 43 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(scheduleUpperPlanName[i]));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 44 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(explainDisp));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 45 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

if (displacement.x > 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 49 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispX));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 49 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardLeftOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 50 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
else if (displacement.x < 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 55 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispX));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 55 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardRightOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 56 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
if (displacement.y > 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 61 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispY));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 61 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardBackOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 62 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
else if (displacement.y < 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 67 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispY));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 67 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardFrontOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 68 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
if (displacement.z > 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 73 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispZ));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 73 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardHeadOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 74 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
else if (displacement.z < 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 79 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispZ));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 79 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardFeetOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 80 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
if (isocentersOnArms && i == 2)
{

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 85 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.IsoOnArmsMarkerWarning));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 86 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
}

            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 92 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.DisplacementsHeader));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 92 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.Legs));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 94 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.MostCaudalIsoFromMarkers));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 94 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lowerMarkersLocation));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 94 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Math.Abs(Math.Round(lowerIsocenters.Last().z, 0)) / 10));
            
            #line default
            #line hidden
            this.Write(" cm\r\n");
            
            #line 95 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.Notes));
            
            #line default
            #line hidden
            this.Write(": ...\r\n");
            
            #line 96 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

for (int i = 0; i < lowerIsocenters.Count; ++i)
{
VVector displacement = i == 0 ? lowerIsocenters[i] : lowerIsocenters[i] - lowerIsocenters[i - 1];
double roundedDispX = Math.Abs(Math.Round(displacement.x, 0)) / 10;
double roundedDispY = Math.Abs(Math.Round(displacement.y, 0)) / 10;
double roundedDispZ = Math.Abs(Math.Round(displacement.z, 0)) / 10;
string explainDisp = i == 0 ?
        string.Join(" ", Resources.WrtMarkersNear, lowerMarkersLocation, Resources.MoveBy)
        : string.Join(" ", Resources.WrtIsocenter, i + upperIsocenters.Count, Resources.MoveBy);

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 108 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.Isocenter));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 108 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i + upperIsocenters.Count + 1));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 108 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(scheduleLowerPlanName[i]));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 109 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(explainDisp));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 110 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

if (displacement.x > 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 114 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispX));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 114 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardRightOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 115 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
else if (displacement.x < 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 120 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispX));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 120 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardLeftOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 121 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
if (displacement.y > 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 126 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispY));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 126 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardBackOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 127 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
else if (displacement.y < 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 132 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispY));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 132 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardFrontOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 133 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
if (displacement.z > 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 138 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispZ));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 138 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardFeetOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 139 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
else if (displacement.z < 0)
{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 144 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(roundedDispZ));
            
            #line default
            #line hidden
            this.Write(" cm ");
            
            #line 144 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Resources.TowardHeadOfPatient));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 145 "E:\TMIAutomation\TMIAutomation\Model\Schedule\Templates\DisplacementsPage.tt"

}
}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DisplacementsPageBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
