name: Build

on:
  push:
    branches-ignore:
      #- master
      - automatic_release
      - test_pull_request

jobs:
  call-build:
    uses: ./.github/workflows/reusable_build.yml
    with:
      upload-artifacts: false